### ISSUE TITLE
能否增加排除指定ajax请求不使用该效果

### ISSUE THREAD

**Issue by yany88** [wuwx/laravel-admin-loading-overlay#1]
作者你好，如题，我的项目中有使用到ajax轮询，安装之后一直显示过渡效果，能否增加一个不需要使用该效果的配置。

**Comment by wuwx** [comment]
非常感谢你的关注，在使用 ajax 轮询请求的时候，可以增加一个参数：global，把这个参数设置为 false，就可以不触发 loading-overlay 效果了：

```
$.ajax({
    "url": "https://helloworld.test/api",
    "global": false
})
```
